### PR TITLE
Update subscribe prop len to account for property type byte

### PR DESCRIPTION
**Pull request by viouyang**
Details about the issue opened here: https://github.com/ntex-rs/ntex-mqtt/issues/103

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add unit test? your change is encoder only, decoder should fail then.

could you also add entry to changes.txt

**Comment by viouyang** [comment]
Fixed a unit test in encode.rs to account for the increased length. So 0x14 should be 0x15. 
Added a unit test for decode that includes subscription id, and it seems like decode still works. Which part of decode do you expect should fail? 

I was looking at this block of code, but not sure how prop_len is accounted for in decode. 
image

**Comment by fafhrd91** [comment]
does new test fails with old code?

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
thanks!

**Pull request merged**
