### PR TITLE
Add example for a custom session

### PR DESCRIPTION
**Pull request by ctron**
closes #6

I am not satisfied with the way I had to specify the `publish_vX` methods now. I was hoping for a simpler approach, maybe you can help.

### CODE REVIEW

**Comment by fafhrd91** [comment]
it is possible to generate service factory, something like

```rust
fn publish_v5() -> impl ServiceFactory<Config = MqttSession, Request = .., Response = .., Error = .., InitError = ..> {
    ntex::fn_factory_with_config(|cfg: MqttSession| async move {
         Ok(ntex::fn_service(move |req: Publish| {
             log::info!(
                "incoming publish ({:?}) : {:?} -> {:?}",
                session.state(),
                publish.id(),
                publish.topic()
            );

            // example: only "my-client-id" may publish
            if session.state().client_id == "my-client-id" {
                 futures::future::ready(Ok(publish.ack()))
            } else {
                 futures::future::ready(Ok(publish.ack().reason_code(PublishAckReason::NotAuthorized)))
            }
         }))
    })
}
```

**Comment by ctron** [comment]
I was hoping for a more compact way. Assuming you have a function like `Fn(Session, Request) -> Response<Error>` … it could auto-generate the service factory. Assuming that `InitError = ()`.

**Comment by fafhrd91** [comment]
you would need special wrapper, it should be easy to implement

**Comment by ctron** [comment]
> you would need special wrapper, it should be easy to implement

Ok, so maybe merge this one, and create a follow up issue, making the solution more elegant.

**Comment by fafhrd91** [comment]
ok, makes sense.

**Pull request merged**
