### PR TITLE
Use default keepalive from `Connect` packet.

### PR DESCRIPTION
**Pull request by vadim-kovalyov**
It would be great if by default `Handshake` can honor keep alive value from `Connect` packet. Application developers can always override it in their handshake handlers if needed.

Ref: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349238
> If the Keep Alive value is non-zero and the Server does not receive a Control Packet from the Client within one and a half times the Keep Alive time period, it MUST disconnect the Network Connection to the Client as if the network had failed [MQTT-3.1.2-24].

### CODE REVIEW

**Comment by fafhrd91** [comment]
as I understand MQTT-3.1.2-24 is about when server sets keep-alive, client keep-alive is not related to server keep-alive.

**Comment by vadim-kovalyov** [comment]
> as I understand MQTT-3.1.2-24 is about when server sets keep-alive, client keep-alive is not related to server keep-alive.

The `MQTT-3.1.2-24` is in [Keep Alive section](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349238) of the CONNECT packet sent from Client to Server. It is about client's keep-alive request. 

There is no Server keep-alive in the spec, as far as I can see. The only thing mentioned is that the Server is allowed to disregard the keep alive value from the CONNECT packet and disconnect the client whenever... but the `MQTT-3.1.2-24` is "more normative requirement", if you will :)

Anyway, the change I'm proposing does not make a lot of difference. It just helps avoid mistakes for app developers (when they don't know about explicit call to `ack.keep_alive(timeout)`, and then clients unexpectedly disconnect :)).

**Comment by fafhrd91** [comment]
but ack.keepalive() is server setting. server drops connection if client does not sends anything within this period of time. so this pr gives client ability to influence server settings

**Comment by vadim-kovalyov** [comment]
> but ack.keepalive() is server setting. server drops connection if client does not sends anything within this period of time. so this pr gives client ability to influence server settings

`[MQTT-3.1.2-24]` specifically says that Server must respect Clients Keep-Alive, doesn't it?

**Comment by fafhrd91** [comment]
> `[MQTT-3.1.2-24]` specifically says that Server must respect Clients Keep-Alive, doesn't it?

it does, but your change has nothing to do with client keep-alive.

**Comment by vadim-kovalyov** [comment]
> > `[MQTT-3.1.2-24]` specifically says that Server must respect Clients Keep-Alive, doesn't it?
> 
> it does, but your change has nothing to do with client keep-alive.

Sorry @fafhrd91, I would need more details on that. How can I make Server respect the Keep Alive value from the Client by default and not disconnect client after 30s of idling?

So, the bug that I had in my application:
- Client connected with KeepAlive = 1800 (30m) and subscribed to some topics. Client does not send any publications.
- Since client had KeepAlive = 1800, the client is not supposed to send any PINGREQ within 1800 sec.
- But the client was disconnected after 30s of idle time. This should not happen by default.

**Comment by fafhrd91** [comment]
set required time explicitly

**Comment by vadim-kovalyov** [comment]
Sorry, @fafhrd91, just closing PRs is counter productive.

> set required time explicitly

Setting time explicitly is not obvious for app developers. A developer would expect that the framework will have the default behavior described in the spec (`MQTT-3.1.2-24`), with the ability to override the keep alive if needed.

I'm adding more people to discussion to get the second opinion.

**Comment by fafhrd91** [comment]
reviewing you teams pr requires so much effort and energy. i will get back after my primary tasks.

**Comment by vadim-kovalyov** [comment]
> reviewing you teams pr requires so much effort and energy. i will get back after my primary tasks.

That's fine, and we appreciate your time @fafhrd91. We also have @dpypin and @nayato who can help with review, I guess... thanks in advance!

**Comment by fafhrd91** [comment]
you should be careful

**Comment by StanLi-ops** [comment]
> > > `[MQTT-3.1.2-24]` specifically says that Server must respect Clients Keep-Alive, doesn't it?
> > 
> > 
> > it does, but your change has nothing to do with client keep-alive.
> 
> Sorry @fafhrd91, I would need more details on that ^. How can I make Server respect the Keep Alive value from the Client by default and not disconnect client after 30s of idling?
> 
> So, the bug that I had in my application:
> 
> * Client connected with KeepAlive = 1800 (30m) and subscribed to some topics. Client does not send any publications.
> * Since client had KeepAlive = 1800, the client is not supposed to send any PINGREQ within 1800 sec.
> * But the client was disconnected after 30s of idle time. This should not happen by default.

Hello, I have encountered the same problem as you before.
What I understand is that keep alive has a default value of ‘30s’ in the source code, but the default value can be modified by calling idle_timeout() or keep_alive() through HandshakeAck.
I don't know if this is the correct way, but I haven't encountered such problems anymore.
Here is the sample code:
```rust
async fn handshake_v3<Io>(
    handshake: v3::Handshake<Io>,
) -> Result<v3::HandshakeAck<Io, MySession>, MyServerError> {
    log::info!("new connection: {:?}", handshake);

    let session = MySession { client_id: handshake.packet().client_id.to_string() };

    let keep_alive = handshake.packet().keep_alive;

    Ok(handshake.ack(session, false).idle_timeout(Seconds::new((keep_alive * 3) / 2)))
}

async fn handshake_v5<Io>(
    handshake: v5::Handshake<Io>,
) -> Result<v5::HandshakeAck<Io, MySession>, MyServerError> {
    log::info!("new connection: {:?}", handshake);

    let session = MySession { client_id: handshake.packet().client_id.to_string() };

    let keep_alive = handshake.packet().keep_alive;

    Ok(handshake.ack(session).keep_alive((keep_alive * 3) / 2))
}
```
Hope this helps you.

**Comment by vadim-kovalyov** [comment]
Thanks @StanLi-ops, I applied the same workaround to manually set `HandshakeAck::keep_alive()`. The main point of this PR is to make the framework take client's keep alive into account by default (protocol says that), with possibility to override it with `HandshakeAck::keep_alive()` if needed.

**Comment by fafhrd91** [comment]
thanks

**Pull request merged**
